# Generated by Django 3.0.3 on 2020-02-07 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200207_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': (('can_buy_game', 'Can buy game'), ('can_play_game', 'Can play game'))},
        ),
    ]
