# Generated by Django 3.0.2 on 2020-02-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=3, max_digits=5)),
                ('description', models.TextField()),
                ('url', models.URLField(default='')),
            ],
        ),
    ]
