# Generated by Django 3.0.2 on 2020-02-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_auto_20200221_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='tags',
        ),
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
